#CUDA_VISIBLE_DEVICES=1 python run_new_ratio.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 5e-4 --patience 50 --edge-feats 64 --run_num_seed 3 --train_ratio 0.03 --layer_norm > dblp_ratio_3_ln.txt
#CUDA_VISIBLE_DEVICES=1 python run_new_ratio.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 5e-4 --patience 50 --edge-feats 64 --run_num_seed 3 --train_ratio 0.02 -layer_norm > dblp_ratio_2_ln.txt
#CUDA_VISIBLE_DEVICES=1 python run_new_ratio.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 5e-4 --patience 50 --edge-feats 64 --run_num_seed 3 --train_ratio 0.01 --layer_norm > dblp_ratio_1_ln.txt
CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 5e-4 --patience 100 --edge-feats 64 --run_num_seed 3 --train_ratio 0.03 --layer_norm --sample 3 > dblp_ratio_3_grand.txt
CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 5e-4 --patience 100 --edge-feats 64 --run_num_seed 3 --train_ratio 0.02 --layer_norm --sample 3 > dblp_ratio_2_grand.txt
CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 5e-4 --patience 100 --edge-feats 64 --run_num_seed 3 --train_ratio 0.01 --layer_norm --sample 3 > dblp_ratio_1_grand.txt
#CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 1e-4 --patience 100 --edge-feats 64 --run_num_seed 3 --train_ratio 0.03 --layer_norm --sample 2 > dblp_ratio_3_grand_wd1e4.txt
#CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 1e-4 --patience 100 --edge-feats 64 --run_num_seed 3 --train_ratio 0.03 --layer_norm --sample 3 > dblp_ratio_3_grand_wd1e4_sample3.txt
#CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 5e-5 --patience 100 --edge-feats 64 --run_num_seed 3 --train_ratio 0.03 --layer_norm --sample 2 > dblp_ratio_3_grand_wd5e5.txt
#CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 5e-5 --patience 100 --edge-feats 64 --run_num_seed 3 --train_ratio 0.03 --layer_norm --sample 3 > dblp_ratio_3_grand_wd5e5_sample3.txt
#CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 16 --num-heads 8 --num-layers 3 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 1e-4 --path ../../data/ --weight-decay 5e-4 --patience 100 --edge-feats 64 --run_num_seed 3 --train_ratio 0.03 --layer_norm > dblp_ratio_3_grand_lr1e4.txt
#CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 16 --num-heads 8 --num-layers 3 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 1e-4 --path ../../data/ --weight-decay 5e-4 --patience 100 --edge-feats 64 --run_num_seed 3 --train_ratio 0.03 --layer_norm --sample 3 > dblp_ratio_3_grand_lr1e4_sample3.txt
#CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 16 --num-heads 8 --num-layers 3 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 5e-4 --patience 100 --edge-feats 64 --run_num_seed 3 --train_ratio 0.03 --layer_norm --sample 1 --lam 0.0 > dblp_ratio_3_grand_no_consis.txt
#CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 5e-4 --patience 50 --edge-feats 64 --run_num_seed 3 --train_ratio 0.02 --layer_norm > dblp_ratio_2_grand.txt
#CUDA_VISIBLE_DEVICES=1 python run_new_ratio_grand.py --hidden-dim 64 --num-heads 8 --num-layers 4 --dataset DBLP --dropout 0.5 --run_num 5  --cuda_device 0 --epoch 500 --lr 5e-4 --path ../../data/ --weight-decay 5e-4 --patience 50 --edge-feats 64 --run_num_seed 3 --train_ratio 0.01 --layer_norm > dblp_ratio_1_grand.txt

